# Generated by Django 5.0.6 on 2024-06-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="quality",
            new_name="quantity",
        ),
    ]
